<?php

/**
 * BaseBlogArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property BlogAuthor $Author
 * 
 * @method BlogAuthor  getAuthor() Returns the current record's "Author" value
 * @method BlogArticle setAuthor() Sets the current record's "Author" value
 * 
 * @author     Your name here
 */
abstract class BaseBlogArticle extends Article
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BlogAuthor as Author', ['local' => 'blog_author_id', 'foreign' => 'id']);
    }
}