<?php

/**
 * BaseUserPermission.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property int $user_id
 * @property int $permission_id
 *
 * @method int            getUserId()       Returns the current record's "user_id" value
 * @method int            getPermissionId() Returns the current record's "permission_id" value
 * @method UserPermission setUserId()       Sets the current record's "user_id" value
 * @method UserPermission setPermissionId() Sets the current record's "permission_id" value
 *
 * @author     Your name here
 */
abstract class BaseUserPermission extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_permission');
        $this->hasColumn('user_id', 'integer', null, [
            'type' => 'integer',
            'primary' => true,
        ]);
        $this->hasColumn('permission_id', 'integer', null, [
            'type' => 'integer',
            'primary' => true,
        ]);

        $this->option('symfony', [
            'form' => false,
            'filter' => false,
        ]);
    }

    public function setUp()
    {
        parent::setUp();
    }
}
