<?php

/**
 * BaseFormGeneratorTest3
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 *
 * @method string             getName() Returns the current record's "name" value
 * @method FormGeneratorTest3 setName() Sets the current record's "name" value
 *
 * @author     Your name here
 */
abstract class BaseFormGeneratorTest3 extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('form_generator_test3');
        $this->hasColumn('name', 'string', 255, ['type' => 'string', 'length' => 255]);

        $this->option('symfony', ['form' => false, 'filter' => false]);
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(['fields' =>
        [0 => 'name']]);
        $this->actAs($i18n0);
    }
}
