<?php

/**
 * BaseAuthorInheritance.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     Your name here
 */
abstract class BaseAuthorInheritance extends Author
{
    public function setUp()
    {
        parent::setUp();
    }
}
