<?php

/**
 * BaseModelFromLinkedSchema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * 
 * @method string                getName() Returns the current record's "name" value
 * @method ModelFromLinkedSchema setName() Sets the current record's "name" value
 * 
 * @author     Your name here
 */
abstract class BaseModelFromLinkedSchema extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('model_from_linked_schema');
        $this->hasColumn('name', 'string', 255, ['type' => 'string', 'length' => 255]);

        $this->option('symfony', ['form' => false, 'filter' => false]);
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}