<?php

/**
 * BaseBlogAuthor
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property Doctrine_Collection $Articles
 *
 * @method Doctrine_Collection getArticles() Returns the current record's "Articles" collection
 * @method BlogAuthor          setArticles() Sets the current record's "Articles" collection
 *
 * @author     Your name here
 */
abstract class BaseBlogAuthor extends Author
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BlogArticle as Articles', ['local' => 'id', 'foreign' => 'blog_author_id']);
    }
}
