<?php

/**
 * BaseAuthorInheritanceConcrete
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $additional
 *
 * @method string                    getAdditional() Returns the current record's "additional" value
 * @method AuthorInheritanceConcrete setAdditional() Sets the current record's "additional" value
 *
 * @author     Your name here
 */
abstract class BaseAuthorInheritanceConcrete extends Author
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('author_inheritance_concrete');
        $this->hasColumn('additional', 'string', 255, ['type' => 'string', 'length' => 255]);
    }

    public function setUp()
    {
        parent::setUp();
    }
}
