<?php

/**
 * BaseFormGeneratorTest
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 *
 * @method string            getName() Returns the current record's "name" value
 * @method FormGeneratorTest setName() Sets the current record's "name" value
 *
 * @author     Your name here
 */
abstract class BaseFormGeneratorTest extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('form_generator_test');
        $this->hasColumn('name', 'string', 255, ['type' => 'string', 'length' => 255]);

        $this->option('symfony', ['form' => true, 'filter' => false]);
    }

    public function setUp()
    {
        parent::setUp();
    }
}
