<?php

/**
 * BaseGroupPermission.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property int $group_id
 * @property int $permission_id
 *
 * @method int             getGroupId()      Returns the current record's "group_id" value
 * @method int             getPermissionId() Returns the current record's "permission_id" value
 * @method GroupPermission setGroupId()      Sets the current record's "group_id" value
 * @method GroupPermission setPermissionId() Sets the current record's "permission_id" value
 *
 * @author     Your name here
 */
abstract class BaseGroupPermission extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('group_permission');
        $this->hasColumn('group_id', 'integer', null, [
            'type' => 'integer',
            'primary' => true,
        ]);
        $this->hasColumn('permission_id', 'integer', null, [
            'type' => 'integer',
            'primary' => true,
        ]);

        $this->option('symfony', [
            'form' => false,
            'filter' => false,
        ]);
    }

    public function setUp()
    {
        parent::setUp();
    }
}
