<?php

/**
 * BaseAttachment.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $file_path
 *
 * @method string     getFilePath() Returns the current record's "file_path" value
 * @method Attachment setFilePath() Sets the current record's "file_path" value
 *
 * @author     Your name here
 */
abstract class BaseAttachment extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attachment');
        $this->hasColumn('file_path', 'string', 255, [
            'type' => 'string',
            'length' => 255,
        ]);
    }

    public function setUp()
    {
        parent::setUp();
    }
}
