<?php

/**
 * BaseUserGroup.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property int $user_id
 * @property int $group_id
 *
 * @method int       getUserId()  Returns the current record's "user_id" value
 * @method int       getGroupId() Returns the current record's "group_id" value
 * @method UserGroup setUserId()  Sets the current record's "user_id" value
 * @method UserGroup setGroupId() Sets the current record's "group_id" value
 *
 * @author     Your name here
 */
abstract class BaseUserGroup extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_group');
        $this->hasColumn('user_id', 'integer', null, [
            'type' => 'integer',
            'primary' => true,
        ]);
        $this->hasColumn('group_id', 'integer', null, [
            'type' => 'integer',
            'primary' => true,
        ]);

        $this->option('symfony', [
            'form' => false,
            'filter' => false,
        ]);
    }

    public function setUp()
    {
        parent::setUp();
    }
}
